import json

# inp_str = " {'k1':123, 'k2': '345',’k3’,’ares’} "
inp_strr = '{"time": 0.004747, "ok": True, "response": {"language": "eng", "properties": [{"wordPositions": [3], "id": 0, "propertyPositions": [2]}], "sentences": [{"words": [{"token": "what", "partOfSpeech": "WP", "relationToParent": "nsubj", "lemma": "what", "startingPos": 0, "endingPos": 4, "stem": "what", "parentPosition": 4, "position": 0}, {"token": "does", "partOfSpeech": "VBZ", "relationToParent": "aux", "lemma": "do", "startingPos": 5, "endingPos": 9, "stem": "doe", "parentPosition": 4, "position": 1}, {"token": "jamaican", "partOfSpeech": "JJ", "relationToParent": "amod", "lemma": "jamaican", "startingPos": 10, "endingPos": 18, "stem": "jamaican", "parentPosition": 3, "position": 2}, {"token": "people", "partOfSpeech": "NNS", "relationToParent": "nsubj", "lemma": "person", "startingPos": 19, "endingPos": 25, "stem": "peopl", "parentPosition": 4, "position": 3}, {"token": "speak", "partOfSpeech": "VBP", "lemma": "speak", "startingPos": 26, "endingPos": 31, "stem": "speak", "position": 4}, {"token": "?", "partOfSpeech": ".", "relationToParent": "punct", "lemma": "?", "startingPos": 31, "endingPos": 32, "stem": "?", "parentPosition": 4, "position": 5}], "position": 0}], "languageIsReliable": True, "entities": [{"freebaseTypes": ["/location/location"], "id": 0, "confidenceScore": 0.5, "matchingTokens": [2], "startingPos": 10, "relevanceScore": 0, "type": ["Place"], "entityEnglishId": "", "matchedText": "jamaican", "wikiLink": "", "endingPos": 18, "entityId": "jamaican"}], "nounPhrases": [{"wordPositions": [0], "id": 0}, {"wordPositions": [2, 3], "id": 1}]}}'
# inp_strr='{"response": {"sentences": [{"position": 0, "words": [{"token": "what", "relationToParent": "nsubj", "startingPos": 0, "parentPosition": 4, "position": 0, "lemma": "what", "endingPos": 4, "partOfSpeech": "WP", "stem": "what"}, {"token": "does", "relationToParent": "aux", "startingPos": 5, "parentPosition": 4, "position": 1, "lemma": "do", "endingPos": 9, "partOfSpeech": "VBZ", "stem": "doe"}, {"token": "jamaican", "relationToParent": "amod", "startingPos": 10, "parentPosition": 3, "position": 2, "lemma": "jamaican", "endingPos": 18, "partOfSpeech": "JJ", "stem": "jamaican"}, {"token": "people", "relationToParent": "nsubj", "startingPos": 19, "parentPosition": 4, "position": 3, "lemma": "person", "endingPos": 25, "partOfSpeech": "NNS", "stem": "peopl"}, {"token": "speak", "startingPos": 26, "position": 4, "lemma": "speak", "endingPos": 31, "partOfSpeech": "VBP", "stem": "speak"}, {"token": "?", "relationToParent": "punct", "startingPos": 31, "parentPosition": 4, "position": 5, "lemma": "?", "endingPos": 32, "partOfSpeech": ".", "stem": "?"}]}], "language": "eng", "properties": [{"wordPositions": [3], "propertyPositions": [2], "id": 0}], "languageIsReliable": True, "entities": [{"type": ["Place"], "confidenceScore": 0.5, "wikiLink": "", "freebaseTypes": ["/location/location"], "startingPos": 10, "endingPos": 18, "entityEnglishId": "", "matchingTokens": [2], "entityId": "jamaican", "relevanceScore": 0, "id": 0, "matchedText": "jamaican"}]}, "ok": True, "time": 0.004139}'
dic=eval(inp_strr)
print(dic)


# print(json.loads(inp_strr))


